name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Các thư viện tiện ích
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # Quản lý trạng thái (Cần cho tính năng Đa ngôn ngữ)
  provider: ^6.1.2

  # Lưu trữ dữ liệu (User, Settings)
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

  # Chọn ảnh từ thư viện (Để đổi avatar)
  image_picker: ^1.1.0

  # Phát nhạc
  audioplayers: ^5.2.1

  # Kết nối mạng & Hiển thị ảnh mạng
  http: ^1.2.0
  cached_network_image: ^3.3.1

  # --- CÁC THƯ VIỆN MỚI THÊM CHO TÍNH NĂNG TẢI & SHARE ---
  dio: ^5.4.3                  # Để tải file nhạc (Download)
  share_plus: ^9.0.0           # Để chia sẻ link nhạc
  permission_handler: ^11.3.1  # Để xin quyền lưu file vào máy
  # -------------------------------------------------------

  # Thông báo (Toast)
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Cấu hình đường dẫn ảnh trong thư mục assets
  assets:
    - assets/images/